export const FETCH_ARTICLES_START = 'FETCH_ARTICLES_START'
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS'
export const FETCH_ARTICLES_FAIL = 'FETCH_ARTICLES_FAIL'

export const FETCH_ARTICLE_START = 'FETCH_ARTICLE_START'
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS'
export const FETCH_ARTICLE_FAIL = 'FETCH_ARTICLE_FAIL'

export const FETCH_TAGS_START = 'FETCH_TAGS_START'
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS'
export const FETCH_TAGS_FAIL = 'FETCH_TAGS_FAIL'

export const FAVORITE_ARTICLE_START = 'FAVORITE_ARTICLE_START'
export const FAVORITE_ARTICLE_SUCCESS = 'FAVORITE_ARTICLE_SUCCESS'

export const UNFAVORITE_ARTICLE_START = 'UNFAVORITE_ARTICLE_START'
export const UNFAVORITE_ARTICLE_SUCCESS = 'UNFAVORITE_ARTICLE_SUCCESS'

export const CREATE_ARTICLE_START = 'CREATE_ARTICLE_START'
export const CREATE_ARTICLE_FAIL = 'CREATE_ARTICLE_FAIL'

export const UPDATE_ARTICLE_START = 'UPDATE_ARTICLE_START'
export const UPDATE_ARTICLE_FAIL = 'UPDATE_ARTICLE_FAIL'

export const DELETE_ARTICLE_START = 'DELETE_ARTICLE_START'
export const DELETE_ARTICLE_FAIL = 'DELETE_ARTICLE_FAIL'

export const CLEAR_ARTICLE = 'CLEAR_ARTICLE'
export const CLEAR_ARTICLES = 'CLEAR_ARTICLES'

//Auth
export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const LOGOUT_START = 'LOGOUT_START'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER'

export const REGISTER_START = 'REGISTER_START'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const CLEAR_ALL_AUTH_ERRORS = 'CLEAR_ALL_AUTH_ERRORS'

//User
export const UPDATE_PROFILE_START = 'UPDATE_PROFILE_START'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

export const GET_PROFILE_START = 'GET_PROFILE_START'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'

export const FOLLOW_PROFILE_START = 'FOLLOW_PROFILE_START'
export const FOLLOW_PROFILE_SUCCESS = 'FOLLOW_PROFILE_SUCCESS'
export const FOLLOW_PROFILE_FAIL = 'FOLLOW_PROFILE_FAIL'

export const UNFOLLOW_PROFILE_START = 'UNFOLLOW_PROFILE_START'
export const UNFOLLOW_PROFILE_SUCCESS = 'UNFOLLOW_PROFILE_SUCCESS'
export const UNFOLLOW_PROFILE_FAIL = 'UNFOLLOW_PROFILE_FAIL'

export const CLEAR_PROFILE = 'CLEAR_PROFILE'

//Pages
export const ARTICLE_PAGE_UNLOAD = 'ARTICLE_PAGE_UNLOAD'